// ─── Live webcam registry ────────────────────────────────────────────────────
// type: 'youtube'  → src is a YouTube video ID (live stream)
//       'jpeg'     → src is a direct JPEG URL that refreshes
//       'iframe'   → src is an embeddable iframe URL
//
// facing: which direction the camera points / is best for
//   'sunset' | 'sunrise' | 'both'

export const WEBCAMS = [
  // ── San Francisco Bay Area ─────────────────────────────────────────────────
  {
    id: 'golden-gate-bridge',
    name: 'Golden Gate Bridge',
    location: 'Crissy Field, SF',
    lat: 37.8033, lon: -122.4649,
    type: 'youtube',
    src: 'BSWhGNXxT9A',
    facing: 'sunset',
    emoji: '🌉',
  },
  {
    id: 'sf-bay',
    name: 'San Francisco Bay',
    location: 'Treasure Island, SF',
    lat: 37.8237, lon: -122.3705,
    type: 'youtube',
    src: 'a5IW4I-z2rs',
    facing: 'both',
    emoji: '🌁',
  },
  {
    id: 'golden-gate-ipcam',
    name: 'Golden Gate (Headlands)',
    location: 'Marin Headlands, SF',
    lat: 37.8297, lon: -122.4995,
    type: 'iframe',
    src: 'https://g1.ipcamlive.com/player/player.php?alias=5e863c6e0e66d&autoplay=1&mute=1',
    facing: 'sunset',
    emoji: '🌉',
  },
  {
    id: 'ocean-beach',
    name: 'Ocean Beach',
    location: 'Ocean Beach, SF',
    lat: 37.7601, lon: -122.5105,
    type: 'jpeg',
    src: 'https://video-monitoring.com/beachcams/oceanbeach/static/s4latest.jpg',
    refreshMs: 30000,
    facing: 'sunset',
    emoji: '🏖',
  },
  {
    id: 'pacifica',
    name: 'Pacifica Cliffs',
    location: 'Pacifica, CA',
    lat: 37.6335, lon: -122.4927,
    type: 'youtube',
    src: 'UYu-TjvAVFs',
    facing: 'sunset',
    emoji: '🪁',
  },
  // ── Southern California ────────────────────────────────────────────────────
  {
    id: 'santa-monica',
    name: 'Santa Monica Pier',
    location: 'Santa Monica, CA',
    lat: 34.0088, lon: -118.4981,
    type: 'youtube',
    src: 'ntbbWgqco4o',
    facing: 'sunset',
    emoji: '🎡',
  },
  {
    id: 'venice-beach',
    name: 'Venice Beach',
    location: 'Venice Beach, CA',
    lat: 33.9850, lon: -118.4695,
    type: 'youtube',
    src: '98jOtUeM3m8',
    facing: 'sunset',
    emoji: '🛼',
  },
  // ── Pacific Northwest ──────────────────────────────────────────────────────
  {
    id: 'seaside-oregon',
    name: 'Seaside Beach',
    location: 'Seaside, Oregon',
    lat: 45.9934, lon: -123.9224,
    type: 'youtube',
    src: 'FyTZdTQfIKw',
    facing: 'sunset',
    emoji: '🌲',
  },
  {
    id: 'tofino-bc',
    name: 'Tofino Long Beach',
    location: 'Tofino, BC, Canada',
    lat: 49.0666, lon: -125.7603,
    type: 'youtube',
    src: 'JZ3UV60ykqc',
    facing: 'sunset',
    emoji: '🍁',
  },
  // ── Hawaii ─────────────────────────────────────────────────────────────────
  {
    id: 'waikiki-beach',
    name: 'Waikiki Beach',
    location: 'Honolulu, Hawaii',
    lat: 21.2767, lon: -157.8278,
    type: 'youtube',
    src: 'X0idnu7HUmI',
    facing: 'sunset',
    emoji: '🌺',
  },
  {
    id: 'kaanapali-maui',
    name: 'Kaanapali Beach',
    location: 'Maui, Hawaii',
    lat: 20.9258, lon: -156.6946,
    type: 'youtube',
    src: 'pY0cgFgMcN0',
    facing: 'sunset',
    emoji: '🌺',
  },
  {
    id: 'lawai-kauai',
    name: 'Lawai Beach',
    location: 'Kauai, Hawaii',
    lat: 21.8958, lon: -159.5205,
    type: 'youtube',
    src: '3ATYHKN2hIg',
    facing: 'sunset',
    emoji: '🌺',
  },
  // ── Florida ────────────────────────────────────────────────────────────────
  {
    id: 'key-west',
    name: 'Key West Southernmost',
    location: 'Key West, Florida',
    lat: 24.5465, lon: -81.7995,
    type: 'youtube',
    src: 'HDlmUp4JBLg',
    facing: 'sunset',
    emoji: '🔑',
  },
  {
    id: 'clearwater-beach',
    name: 'Clearwater Beach',
    location: 'Clearwater, Florida',
    lat: 27.9777, lon: -82.8285,
    type: 'youtube',
    src: '2jgXAQTOAlw',
    facing: 'sunset',
    emoji: '🏖',
  },
  // ── Mexico ─────────────────────────────────────────────────────────────────
  {
    id: 'puerto-vallarta',
    name: 'Puerto Vallarta',
    location: 'Puerto Vallarta, Mexico',
    lat: 20.6058, lon: -105.2405,
    type: 'youtube',
    src: 'RY3iDXftbMc',
    facing: 'sunset',
    emoji: '🌮',
  },
  {
    id: 'cabo-san-lucas',
    name: 'Cabo San Lucas',
    location: 'Cabo San Lucas, Mexico',
    lat: 22.8905, lon: -109.9167,
    type: 'youtube',
    src: 'E85vFalANCo',
    facing: 'sunset',
    emoji: '🌵',
  },
  // ── Costa Rica ─────────────────────────────────────────────────────────────
  {
    id: 'tamarindo-beach',
    name: 'Tamarindo Beach',
    location: 'Tamarindo, Costa Rica',
    lat: 10.2993, lon: -85.8378,
    type: 'iframe',
    src: 'https://v.angelcam.com/iframe?v=16rb3v4xy4&autoplay=1',
    facing: 'sunset',
    emoji: '🌴',
  },
  // ── Europe ─────────────────────────────────────────────────────────────────
  {
    id: 'ibiza',
    name: 'Ibiza',
    location: 'Ibiza, Spain',
    lat: 38.9076, lon: 1.4206,
    type: 'youtube',
    src: 'f6tsHCx4-3g',
    facing: 'sunset',
    emoji: '🌊',
  },
  {
    id: 'portimao-algarve',
    name: 'Portimão Marina',
    location: 'Algarve, Portugal',
    lat: 37.1340, lon: -8.5296,
    type: 'youtube',
    src: 'w7rzgn6WXs8',
    facing: 'sunset',
    emoji: '🇵🇹',
  },
  // ── Japan ──────────────────────────────────────────────────────────────────
  {
    id: 'mount-fuji',
    name: 'Mount Fuji',
    location: 'Kawaguchiko, Japan',
    lat: 35.5060, lon: 138.7778,
    type: 'youtube',
    src: 'Sv9hcJ3k5h4',
    facing: 'both',
    emoji: '🗻',
  },
  {
    id: 'mount-fuji-jpeg',
    name: 'Mount Fuji Live',
    location: 'Fujigoko, Japan',
    lat: 35.4972, lon: 138.7544,
    type: 'jpeg',
    src: 'https://cam.fujigoko.tv/livecam3/s/cam.jpg',
    refreshMs: 60000,
    facing: 'both',
    emoji: '🗻',
  },
  // ── Bali, Indonesia ────────────────────────────────────────────────────────
  {
    id: 'uluwatu-bali',
    name: 'Uluwatu Beach',
    location: 'Uluwatu, Bali',
    lat: -8.8291, lon: 115.0849,
    type: 'youtube',
    src: 'g3wF5i-BEzo',
    facing: 'sunset',
    emoji: '🌴',
  },
  // ── New Zealand ────────────────────────────────────────────────────────────
  {
    id: 'kaiteriteri-nz',
    name: 'Kaiteriteri Beach',
    location: 'Nelson-Tasman, NZ',
    lat: -40.9979, lon: 173.0174,
    type: 'youtube',
    src: 'rknjxMtee8A',
    facing: 'sunset',
    emoji: '🥝',
  },
  // ── India ──────────────────────────────────────────────────────────────────
  {
    id: 'delhi-live',
    name: 'New Delhi',
    location: 'Delhi, India',
    lat: 28.6139, lon: 77.2090,
    type: 'iframe',
    src: 'https://g0.ipcamlive.com/player/player.php?alias=aqi02&autoplay=1&mute=1',
    facing: 'both',
    emoji: '🕌',
  },
];
